// GDevelop — Visual game engine kernel: event sheets, object layers, condition-action system.
// Generated by the Counted Repo Factory (seeds/seeds.yaml). Deterministic by construction.
// Layout: docs/REPO_STANDARD.md — core logic in src/lib/, public API in src/index.ts.

import { seededRandom } from "./lib/rng";
import { EventSheets, ObjectLayers, ConditionActions } from "./lib/modules";

export const SPEC = "Visual game engine kernel: event sheets, object layers, condition-action system.";
export const MODULES = [{ id: "EventSheets", name: "GDevelop :: EventSheets" }, { id: "ObjectLayers", name: "GDevelop :: ObjectLayers" }, { id: "ConditionActions", name: "GDevelop :: ConditionActions" }];
export { seededRandom };
export class Registry {
  private items = new Map<string, string>();
  constructor(seed = 42) {
    const rng = seededRandom(seed);
    for (const mod of MODULES) {
      const n = 1 + Math.floor(rng() * 4);
      for (let i = 0; i < n; i++) {
        this.items.set(mod.id + "-" + i, mod.name);
      }
    }
  }
  count(): number { return this.items.size; }
  get(id: string): string | undefined { return this.items.get(id); }
  ids(): string[] { return [...this.items.keys()]; }
  lookup(name: string): string[] {
    return this.ids().filter((id) => this.items.get(id) === name);
  }
}
